[project]
name = "mkp"
version = "0.1.0"
description = "Řešení okrajové úlohy Poissonovy rovnice metodou konečných prvků"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "plotly>=6.5.2",
    "scipy>=1.18.1",
    "scipy-stubs>=1.18.1.0",
]
